### ISSUE TITLE
Package guzzle/guzzle is abandoned, ... Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by andygrunwald** [instaclick/medusa#15]
The message `Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.` appears in a composer install.

**Comment by robocoder** [comment]
We can probably switch to a curl extension dependency to shrink the footprint and number of dependencies pulled in.

**Comment by andygrunwald** [comment]
PR to fix this is in #25 
I decided to not replace guzzle for now. This dependency don't hurt here and it works quite well right now.
