### ISSUE TITLE
No phar files to download

### ISSUE THREAD

**Issue by wvdvegt** [instaclick/medusa#28]
Where can i find the files mentioned in the readme.md?

- Download the .phar archive from the downloads section
- Download the .phar archive for SATIS

**Comment by robocoder** [comment]
Sorry, the readme needs to be updated.

You can find the phar files in the respective `bin` folders.

https://github.com/composer/satis/tree/master/bin
https://github.com/instaclick/medusa/tree/master/bin

**Comment by wvdvegt** [comment]
I found them there, issue is they have no .phar extension so i overlooked them.
